<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core\**" />
    <EmbeddedResource Remove="Core\**" />
    <None Remove="Core\**" />
    <Page Remove="Core\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Presentation\Controls\" />
    <Folder Include="Presentation\Pages\Models\" />
    <Folder Include="Presentation\Pages\ViewModels\" />
    <Folder Include="Presentation\Shell\Views\" />
    <Folder Include="Resources\Themes\Layout\" />
    <Folder Include="Resources\Themes\Controls\" />
  </ItemGroup>

</Project>
